FORWARD = 'w'
BACKWARD = 's'
LEFT = 'a'
RIGHT = 'd'
ZERO_LEFT = 'q'
ZERO_RIGHT = 'e'
LINE_TRACK = 'x'

FIRST_GEAR = 'y'
SECOND_GEAR = 'u'
THIRD_GEAR = 'i'
FOURTH_GEAR = 'o'
FIFTH_GEAR = 'p'

TURN_VERY_SLOW = 'h'
TURN_SLOW = 'j'
TURN_MEDIUM = 'k'
TURN_FAST = 'l'
TURN_VERY_FAST = ';'

DRIFT_LEFT_4 = '1'
DRIFT_LEFT_3 = '2'
DRIFT_LEFT_2 = '3'
DRIFT_LEFT_1 = '4'
DRIFT_NONE = '5'
DRIFT_RIGHT_1 = '6'
DRIFT_RIGHT_2 = '7'
DRIFT_RIGHT_3 = '8'
DRIFT_RIGHT_4 = '9'

LED_OFF = 'v'
LED_DESIGN_1 = 'b'
LED_DESIGN_2 = 'n'
LED_DESIGN_3 = 'm'
LED_DESIGN_4 = ','
LED_DESIGN_5 = '.'

GEAR_KEYS = [FIRST_GEAR, SECOND_GEAR, THIRD_GEAR, FOURTH_GEAR, FIFTH_GEAR]
TURN_KEYS = [TURN_VERY_SLOW, TURN_SLOW, TURN_MEDIUM, TURN_FAST, TURN_VERY_FAST]
DRIFT_KEYS = [DRIFT_LEFT_4, DRIFT_LEFT_3, DRIFT_LEFT_2, DRIFT_LEFT_1, DRIFT_NONE,
              DRIFT_RIGHT_1, DRIFT_RIGHT_2, DRIFT_RIGHT_3, DRIFT_RIGHT_4]
LED_KEYS = [LED_OFF, LED_DESIGN_1, LED_DESIGN_2, LED_DESIGN_3, LED_DESIGN_4, LED_DESIGN_5]